# Autogenerated wrapper script for Qt5Base_jll for aarch64-apple-darwin
export libqt5concurrent, libqt5core, libqt5dbus, libqt5gui, libqt5network, libqt5opengl, libqt5printsupport, libqt5sql, libqt5test, libqt5widgets, libqt5xml

using Xorg_libXext_jll
using Xorg_libxcb_jll
using Xorg_xcb_util_wm_jll
using Xorg_xcb_util_image_jll
using Xorg_xcb_util_keysyms_jll
using Xorg_xcb_util_renderutil_jll
using xkbcommon_jll
using Libglvnd_jll
using Fontconfig_jll
using Glib_jll
using Zlib_jll
using CompilerSupportLibraries_jll
using OpenSSL_jll
JLLWrappers.@generate_wrapper_header("Qt5Base")
JLLWrappers.@declare_library_product(libqt5concurrent, "@rpath/QtConcurrent")
JLLWrappers.@declare_library_product(libqt5core, "@rpath/QtCore")
JLLWrappers.@declare_library_product(libqt5dbus, "@rpath/QtDBus")
JLLWrappers.@declare_library_product(libqt5gui, "@rpath/QtGui")
JLLWrappers.@declare_library_product(libqt5network, "@rpath/QtNetwork")
JLLWrappers.@declare_library_product(libqt5opengl, "@rpath/QtOpenGL")
JLLWrappers.@declare_library_product(libqt5printsupport, "@rpath/QtPrintSupport")
JLLWrappers.@declare_library_product(libqt5sql, "@rpath/QtSql")
JLLWrappers.@declare_library_product(libqt5test, "@rpath/QtTest")
JLLWrappers.@declare_library_product(libqt5widgets, "@rpath/QtWidgets")
JLLWrappers.@declare_library_product(libqt5xml, "@rpath/QtXml")
function __init__()
    JLLWrappers.@generate_init_header(Xorg_libXext_jll, Xorg_libxcb_jll, Xorg_xcb_util_wm_jll, Xorg_xcb_util_image_jll, Xorg_xcb_util_keysyms_jll, Xorg_xcb_util_renderutil_jll, xkbcommon_jll, Libglvnd_jll, Fontconfig_jll, Glib_jll, Zlib_jll, CompilerSupportLibraries_jll, OpenSSL_jll)
    JLLWrappers.@init_library_product(
        libqt5concurrent,
        "lib/QtConcurrent.framework/Versions/5/QtConcurrent",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5core,
        "lib/QtCore.framework/Versions/5/QtCore",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5dbus,
        "lib/QtDBus.framework/Versions/5/QtDBus",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5gui,
        "lib/QtGui.framework/Versions/5/QtGui",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5network,
        "lib/QtNetwork.framework/Versions/5/QtNetwork",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5opengl,
        "lib/QtOpenGL.framework/Versions/5/QtOpenGL",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5printsupport,
        "lib/QtPrintSupport.framework/Versions/5/QtPrintSupport",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5sql,
        "lib/QtSql.framework/Versions/5/QtSql",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5test,
        "lib/QtTest.framework/Versions/5/QtTest",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5widgets,
        "lib/QtWidgets.framework/Versions/5/QtWidgets",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5xml,
        "lib/QtXml.framework/Versions/5/QtXml",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
