[[Qt5Base]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f68fcf026f0f6cf2854c6751d50371b007ef4e40"
libc = "glibc"
os = "linux"

    [[Qt5Base.download]]
    sha256 = "4a0c300e47c39feff899499c993e727d7f444eeabeecd74760a275ceb6e12713"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+0/Qt5Base.v5.15.3.aarch64-linux-gnu-cxx03.tar.gz"
[[Qt5Base]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b961a0b816e2f473c9cf5f67f44cd07b1a595f87"
libc = "glibc"
os = "linux"

    [[Qt5Base.download]]
    sha256 = "b62fb7a4e9dd335c23e62330fb8d2a3c78e6a5be8e921687c7db5131c0a73c42"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+0/Qt5Base.v5.15.3.aarch64-linux-gnu-cxx11.tar.gz"
[[Qt5Base]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e2b2e3f39729b9bf5014d4346d5d21fae5fdc4f8"
libc = "glibc"
os = "linux"

    [[Qt5Base.download]]
    sha256 = "ebb294cf80aa02613c267ac78131f70d0c62686a5a41f31bf8b76bba4e397821"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+0/Qt5Base.v5.15.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Qt5Base]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e257321d734c019bd89a43d1f4ae98cd263dd0ab"
libc = "glibc"
os = "linux"

    [[Qt5Base.download]]
    sha256 = "44a3c93b202528ec87711b290ff24dc4832ec4c978e1f713b62c8040f020c05e"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+0/Qt5Base.v5.15.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Qt5Base]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f5dbc5dd2d63c23e645cc82632c788ae3a9e10c4"
libc = "glibc"
os = "linux"

    [[Qt5Base.download]]
    sha256 = "c190e3706555dd988ab0fef0768369c23fa9200d35393cad3fa06eb0a7515bdf"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+0/Qt5Base.v5.15.3.i686-linux-gnu-cxx03.tar.gz"
[[Qt5Base]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "16e4067c64108be4a3bb4be0abc0438f791b0b5c"
libc = "glibc"
os = "linux"

    [[Qt5Base.download]]
    sha256 = "97aff27e0cf5653a532fcc8173f4c8ea8060bf2a89a26e10fe3cfe78e751b3ce"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+0/Qt5Base.v5.15.3.i686-linux-gnu-cxx11.tar.gz"
[[Qt5Base]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6de3f7ad8be1521f40b812b2ef975408bdec7f40"
libc = "glibc"
os = "linux"

    [[Qt5Base.download]]
    sha256 = "717d55f020e512d19a8781d78a6d2b8b248cb00c36ee0298a37ff8ef6c583e2e"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+0/Qt5Base.v5.15.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Qt5Base]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "73bd71408b091e11827600e4c12c608d1ab14374"
libc = "glibc"
os = "linux"

    [[Qt5Base.download]]
    sha256 = "475bd2f89d1bbe4b5d958719faefe3a1c0f7671d9bff7f9b2f12262609fc9b85"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+0/Qt5Base.v5.15.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Qt5Base]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "386e781dc77c029582aace7dfe3fd16fc5abf630"
libc = "glibc"
os = "linux"

    [[Qt5Base.download]]
    sha256 = "77f885cd7a86cfd962d00e851cbe4608169ef2cf78e8ffde0a1503cf66a9e669"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+0/Qt5Base.v5.15.3.x86_64-linux-gnu-cxx03.tar.gz"
[[Qt5Base]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f88efb2d9aedf42ee5bf6069eddfe226653e93e6"
libc = "glibc"
os = "linux"

    [[Qt5Base.download]]
    sha256 = "2a499a1fd8a43206ee38df3f1093c22e5285a48872e30b9de2c0d63b61933073"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+0/Qt5Base.v5.15.3.x86_64-linux-gnu-cxx11.tar.gz"
[[Qt5Base]]
arch = "x86_64"
git-tree-sha1 = "3cc1e559b362076118d4657b6957532874357e74"
os = "freebsd"

    [[Qt5Base.download]]
    sha256 = "bf9d06c4c02f8f921a5c1f8d9b802c06745d80afa2741a6d4ab1ae423b03ecbd"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+0/Qt5Base.v5.15.3.x86_64-unknown-freebsd.tar.gz"
[[Qt5Base]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "94d433c3912249b4b2b7d16b8ef5458d75240ee3"
os = "windows"

    [[Qt5Base.download]]
    sha256 = "fc5b042b0f7ffedff64db8608c363050443aaef48b8442091fac10429305c4c1"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+0/Qt5Base.v5.15.3.i686-w64-mingw32-cxx03.tar.gz"
[[Qt5Base]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd77dbd90177cd5a12b2ed7f70c5405ddc94e697"
os = "windows"

    [[Qt5Base.download]]
    sha256 = "04243b5839d5c0a3d60b46f48bad84ed0b85cedbede5bbf9b4dcc747f174d4b0"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+0/Qt5Base.v5.15.3.i686-w64-mingw32-cxx11.tar.gz"
[[Qt5Base]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0cd0303110eea008b3298dcacaeaa8659f150840"
os = "windows"

    [[Qt5Base.download]]
    sha256 = "39b2cd716e6ea5cfe7957fe45bdb801dc841951b51712983e4736798653c113c"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+0/Qt5Base.v5.15.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[Qt5Base]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2ca1bc23171a906b0de66ce0428f60b84d91e2e3"
os = "windows"

    [[Qt5Base.download]]
    sha256 = "4cdfce716ed71c0c434e5af4e33f0d3e7298afa884b6e9658c560095e80d0212"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+0/Qt5Base.v5.15.3.x86_64-w64-mingw32-cxx11.tar.gz"
[[Qt5Base]]
arch = "aarch64"
git-tree-sha1 = "925fb21050dc7cf730aff81b8327939b68015fe2"
os = "macos"

    [[Qt5Base.download]]
    sha256 = "35d7893cb683e968c2a73735220c0aa0aa3c1aa742a71befb530a1d8e217f413"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+0/Qt5Base.v5.15.3.aarch64-apple-darwin.tar.gz"
[[Qt5Base]]
arch = "x86_64"
git-tree-sha1 = "d594d9e68b9d104aaf1a41d933728d2dad54c869"
os = "macos"

    [[Qt5Base.download]]
    sha256 = "bfab53d58c7e5ef49df4d3a9d2679697df1b6ec5ea7b356d20020c141cb2e515"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+0/Qt5Base.v5.15.3.x86_64-apple-darwin.tar.gz"
