[[ASL]]
arch = "aarch64"
git-tree-sha1 = "00849a1d05de4fd114efa5550353445a7c4edc67"
os = "macos"

    [[ASL.download]]
    sha256 = "05f4cb187281d796c1d0807beaf22a6f6afbf1b3b419279f81fdc2783582e38a"
    url = "https://github.com/JuliaBinaryWrappers/ASL_jll.jl/releases/download/ASL-v0.1.3+0/ASL.v0.1.3.aarch64-apple-darwin.tar.gz"
[[ASL]]
arch = "aarch64"
git-tree-sha1 = "279c9a00ab09447222af0629ba6e157ed304c6d3"
libc = "glibc"
os = "linux"

    [[ASL.download]]
    sha256 = "c66e452653dc6c4489acfc1571c8935ae020f92941f18d8bab8cf324c7463863"
    url = "https://github.com/JuliaBinaryWrappers/ASL_jll.jl/releases/download/ASL-v0.1.3+0/ASL.v0.1.3.aarch64-linux-gnu.tar.gz"
[[ASL]]
arch = "aarch64"
git-tree-sha1 = "7b1e799e331c2115292165660579f3817fdaa220"
libc = "musl"
os = "linux"

    [[ASL.download]]
    sha256 = "3d6520e3305391b5227ee4ffa7f8ac644ff866f48ce8703ea80c3745316b01ad"
    url = "https://github.com/JuliaBinaryWrappers/ASL_jll.jl/releases/download/ASL-v0.1.3+0/ASL.v0.1.3.aarch64-linux-musl.tar.gz"
[[ASL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f11df8280b634008a80f8a64d62b576fbb2a8376"
libc = "glibc"
os = "linux"

    [[ASL.download]]
    sha256 = "f717e3c3edf65e5dc5632f87145a2bebb91dad092d9441e5e1b4390cec55a903"
    url = "https://github.com/JuliaBinaryWrappers/ASL_jll.jl/releases/download/ASL-v0.1.3+0/ASL.v0.1.3.armv6l-linux-gnueabihf.tar.gz"
[[ASL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "db970e1a17d8a8b9b39e24a616231482f9615f3c"
libc = "musl"
os = "linux"

    [[ASL.download]]
    sha256 = "bdf7a0ef36249e6cbf5c491a3e438e3abe577ab8ef186eb3d960ec531670bd43"
    url = "https://github.com/JuliaBinaryWrappers/ASL_jll.jl/releases/download/ASL-v0.1.3+0/ASL.v0.1.3.armv6l-linux-musleabihf.tar.gz"
[[ASL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9e2aab064c3358b4c7694e5ba80f6add69aabe27"
libc = "glibc"
os = "linux"

    [[ASL.download]]
    sha256 = "833be5ae2badaa563a63e19505ce1887d300e2ac5406041213e2a7875b232c13"
    url = "https://github.com/JuliaBinaryWrappers/ASL_jll.jl/releases/download/ASL-v0.1.3+0/ASL.v0.1.3.armv7l-linux-gnueabihf.tar.gz"
[[ASL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dcd9296ec755c1e297f6e8ea732a0a3136f3a228"
libc = "musl"
os = "linux"

    [[ASL.download]]
    sha256 = "0f2a0c9305515eb48b8f40b071de95066cda82f36eb4f66a742dbde572531bdf"
    url = "https://github.com/JuliaBinaryWrappers/ASL_jll.jl/releases/download/ASL-v0.1.3+0/ASL.v0.1.3.armv7l-linux-musleabihf.tar.gz"
[[ASL]]
arch = "i686"
git-tree-sha1 = "7ca5e886ec676f441d084edcc2496de5da311cee"
libc = "glibc"
os = "linux"

    [[ASL.download]]
    sha256 = "4c3b9016becece719245564be2b70c2d97f35429ac833f823b019bc515a17df1"
    url = "https://github.com/JuliaBinaryWrappers/ASL_jll.jl/releases/download/ASL-v0.1.3+0/ASL.v0.1.3.i686-linux-gnu.tar.gz"
[[ASL]]
arch = "i686"
git-tree-sha1 = "4585c517160ad7645aae3ea995d2d5302b2d919a"
libc = "musl"
os = "linux"

    [[ASL.download]]
    sha256 = "b0195676117b7c74ff205c2647e4a3f2da622287b8d4268a985a9c9620edc6af"
    url = "https://github.com/JuliaBinaryWrappers/ASL_jll.jl/releases/download/ASL-v0.1.3+0/ASL.v0.1.3.i686-linux-musl.tar.gz"
[[ASL]]
arch = "i686"
git-tree-sha1 = "e0f5ba50561cc7ee61ef31732d5510958e3df85e"
os = "windows"

    [[ASL.download]]
    sha256 = "f659ef9dca59820959d9b19508e1b2d9d1a8cbb460da2a555cc0031fbc36236c"
    url = "https://github.com/JuliaBinaryWrappers/ASL_jll.jl/releases/download/ASL-v0.1.3+0/ASL.v0.1.3.i686-w64-mingw32.tar.gz"
[[ASL]]
arch = "powerpc64le"
git-tree-sha1 = "5835785555b6eb7c6bf5b9e6093546708b251eca"
libc = "glibc"
os = "linux"

    [[ASL.download]]
    sha256 = "6f8922921ad39155e43d0b2892fa182a0f658a117d629a924a6ac4e88b3893e3"
    url = "https://github.com/JuliaBinaryWrappers/ASL_jll.jl/releases/download/ASL-v0.1.3+0/ASL.v0.1.3.powerpc64le-linux-gnu.tar.gz"
[[ASL]]
arch = "x86_64"
git-tree-sha1 = "33a205d3c48459be7e3469081953851a2e945aef"
os = "macos"

    [[ASL.download]]
    sha256 = "c567a5160dea06e52db1572f07b75e50523e691d6b330d02e0a2d02fe53ed4fb"
    url = "https://github.com/JuliaBinaryWrappers/ASL_jll.jl/releases/download/ASL-v0.1.3+0/ASL.v0.1.3.x86_64-apple-darwin.tar.gz"
[[ASL]]
arch = "x86_64"
git-tree-sha1 = "552b43f8dea17007536f11ed23b39fb7e97bec6b"
libc = "glibc"
os = "linux"

    [[ASL.download]]
    sha256 = "2a749c9114cb15543f50706a5e2a5f9b40e0b7def6d0f081fe42721da7e8b610"
    url = "https://github.com/JuliaBinaryWrappers/ASL_jll.jl/releases/download/ASL-v0.1.3+0/ASL.v0.1.3.x86_64-linux-gnu.tar.gz"
[[ASL]]
arch = "x86_64"
git-tree-sha1 = "26ccdf4f03991cf052cf65c64239aa55b89fabd0"
libc = "musl"
os = "linux"

    [[ASL.download]]
    sha256 = "4478ab1977d6059995a96dcef7d8cd510df9da1662d0111eab3d7a016d727df4"
    url = "https://github.com/JuliaBinaryWrappers/ASL_jll.jl/releases/download/ASL-v0.1.3+0/ASL.v0.1.3.x86_64-linux-musl.tar.gz"
[[ASL]]
arch = "x86_64"
git-tree-sha1 = "dc891e5bf3d3d9155ce118da1577061e77a3fdd1"
os = "freebsd"

    [[ASL.download]]
    sha256 = "51707df19ca45f90557cbfd7f5f431fe15cb8db5fbea93a781bc1e887e8ae125"
    url = "https://github.com/JuliaBinaryWrappers/ASL_jll.jl/releases/download/ASL-v0.1.3+0/ASL.v0.1.3.x86_64-unknown-freebsd.tar.gz"
[[ASL]]
arch = "x86_64"
git-tree-sha1 = "71e11f46abe5ae4d2f0f994fc1221227a8b4c2cd"
os = "windows"

    [[ASL.download]]
    sha256 = "1471833a23bec5cd663ec45647089f7a51d59c70853af7f3ef002a26e466856b"
    url = "https://github.com/JuliaBinaryWrappers/ASL_jll.jl/releases/download/ASL-v0.1.3+0/ASL.v0.1.3.x86_64-w64-mingw32.tar.gz"
