language: julia
os:
  - linux
  - osx
addons:
  homebrew:
    packages:
      - cairo
    update: true
julia:
  - 1.0
  - 1.2
  - 1.3
  - nightly
notifications:
  email: false
after_success:
  - julia -e 'if VERSION >= "v0.7-"; using Pkg; else ; cd(Pkg.dir("BinDeps")); end; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())';
