[[Ogg]]
arch = "aarch64"
git-tree-sha1 = "2e2b61385382c417358dc261c5683fef2eb79d0a"
os = "macos"

    [[Ogg.download]]
    sha256 = "7527774902ccd76971821911e1729fa9c3fa73108556b2f795d22e7193226a23"
    url = "https://github.com/JuliaBinaryWrappers/Ogg_jll.jl/releases/download/Ogg-v1.3.5+0/Ogg.v1.3.5.aarch64-apple-darwin.tar.gz"
[[Ogg]]
arch = "aarch64"
git-tree-sha1 = "60c10cc65ad267c221b8b96e7fced9324373ad58"
libc = "glibc"
os = "linux"

    [[Ogg.download]]
    sha256 = "8be01dba1e87cf90ce6d15b3d2d4fabb3d9a24c43117ed163e23da7f5db152e0"
    url = "https://github.com/JuliaBinaryWrappers/Ogg_jll.jl/releases/download/Ogg-v1.3.5+0/Ogg.v1.3.5.aarch64-linux-gnu.tar.gz"
[[Ogg]]
arch = "aarch64"
git-tree-sha1 = "f45541b9a5419a194a6dda8c0cbb55b4bef354a1"
libc = "musl"
os = "linux"

    [[Ogg.download]]
    sha256 = "49fcc7bcce473646bd91c4076e3d5921f9566c2f53f813180f92adccd80c035a"
    url = "https://github.com/JuliaBinaryWrappers/Ogg_jll.jl/releases/download/Ogg-v1.3.5+0/Ogg.v1.3.5.aarch64-linux-musl.tar.gz"
[[Ogg]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "23611fd706052be288905a41846916f168c1cd26"
libc = "glibc"
os = "linux"

    [[Ogg.download]]
    sha256 = "f81dfbb998a502ce25972991f05f5cbc29c966ad9b8dbc397176def60744ec7e"
    url = "https://github.com/JuliaBinaryWrappers/Ogg_jll.jl/releases/download/Ogg-v1.3.5+0/Ogg.v1.3.5.armv6l-linux-gnueabihf.tar.gz"
[[Ogg]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1438910c7fdf5624027d439d3b1aa409435f1e5c"
libc = "musl"
os = "linux"

    [[Ogg.download]]
    sha256 = "e8ba7b8e108c9733b7db41ae0fd30f5b54eb5a46faf16d05fddfc6d8318b1a87"
    url = "https://github.com/JuliaBinaryWrappers/Ogg_jll.jl/releases/download/Ogg-v1.3.5+0/Ogg.v1.3.5.armv6l-linux-musleabihf.tar.gz"
[[Ogg]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3c1cde94424343f15e441161386f3b415f5524ef"
libc = "glibc"
os = "linux"

    [[Ogg.download]]
    sha256 = "c7e747f835699d6ac70c2648c1b57cef6c7a7c2d1c0802a4bdb4f6aa1a2e083a"
    url = "https://github.com/JuliaBinaryWrappers/Ogg_jll.jl/releases/download/Ogg-v1.3.5+0/Ogg.v1.3.5.armv7l-linux-gnueabihf.tar.gz"
[[Ogg]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "70364cc9c793f0e6cebb8ea9fb097d686ae022cb"
libc = "musl"
os = "linux"

    [[Ogg.download]]
    sha256 = "008f5491e0048acb04ce08023aa2618e7ec7b0c377e50fc255309fd76bca0ce0"
    url = "https://github.com/JuliaBinaryWrappers/Ogg_jll.jl/releases/download/Ogg-v1.3.5+0/Ogg.v1.3.5.armv7l-linux-musleabihf.tar.gz"
[[Ogg]]
arch = "i686"
git-tree-sha1 = "0ca2b210f70bf557c6922ab091ec5298cbf65370"
libc = "glibc"
os = "linux"

    [[Ogg.download]]
    sha256 = "a8ba5e7f96c1018f36b0ef31deb6f79963046333519c3568483344ac57015aca"
    url = "https://github.com/JuliaBinaryWrappers/Ogg_jll.jl/releases/download/Ogg-v1.3.5+0/Ogg.v1.3.5.i686-linux-gnu.tar.gz"
[[Ogg]]
arch = "i686"
git-tree-sha1 = "30fc3419a19e69120d6aceab1e4b1ee4e67cff6b"
libc = "musl"
os = "linux"

    [[Ogg.download]]
    sha256 = "8cd7297ba4275bcf9ee422f13aa39d9997849a67b71f14a965414b5271c8832f"
    url = "https://github.com/JuliaBinaryWrappers/Ogg_jll.jl/releases/download/Ogg-v1.3.5+0/Ogg.v1.3.5.i686-linux-musl.tar.gz"
[[Ogg]]
arch = "i686"
git-tree-sha1 = "c99eb9ba29b6f35a418b6c320aab83884dbc273b"
os = "windows"

    [[Ogg.download]]
    sha256 = "c0221bee439aee7f89acde9ce42416ab5816e51717cfe2dc77ff3c06c119f819"
    url = "https://github.com/JuliaBinaryWrappers/Ogg_jll.jl/releases/download/Ogg-v1.3.5+0/Ogg.v1.3.5.i686-w64-mingw32.tar.gz"
[[Ogg]]
arch = "powerpc64le"
git-tree-sha1 = "f3cfb7dcbfaa4c2cd1a46b296f1ee466971f583b"
libc = "glibc"
os = "linux"

    [[Ogg.download]]
    sha256 = "377b9dd06534f5bc045e229e25950ae877c3c08e388c4ab297eb63198116cefd"
    url = "https://github.com/JuliaBinaryWrappers/Ogg_jll.jl/releases/download/Ogg-v1.3.5+0/Ogg.v1.3.5.powerpc64le-linux-gnu.tar.gz"
[[Ogg]]
arch = "x86_64"
git-tree-sha1 = "f356cb8a225f8562e4d62789a9efa010d153ed00"
os = "macos"

    [[Ogg.download]]
    sha256 = "0ae52d712c74ebe5419b34427121444b28067458fa658469b01f51f14603f489"
    url = "https://github.com/JuliaBinaryWrappers/Ogg_jll.jl/releases/download/Ogg-v1.3.5+0/Ogg.v1.3.5.x86_64-apple-darwin.tar.gz"
[[Ogg]]
arch = "x86_64"
git-tree-sha1 = "ef6a9017041e93ab0a4893b551d8893de69b0d97"
libc = "glibc"
os = "linux"

    [[Ogg.download]]
    sha256 = "0dcc21ed6624d3b5b96ba8f7dff538777bc4c919ed4e136215e332666aaa458f"
    url = "https://github.com/JuliaBinaryWrappers/Ogg_jll.jl/releases/download/Ogg-v1.3.5+0/Ogg.v1.3.5.x86_64-linux-gnu.tar.gz"
[[Ogg]]
arch = "x86_64"
git-tree-sha1 = "97eb88b8565611b93aa53e432545c2e731aa5297"
libc = "musl"
os = "linux"

    [[Ogg.download]]
    sha256 = "bac8b0677e6a0d30a77f2c55092c3504e045380214184c25a35a69b2d95dd81f"
    url = "https://github.com/JuliaBinaryWrappers/Ogg_jll.jl/releases/download/Ogg-v1.3.5+0/Ogg.v1.3.5.x86_64-linux-musl.tar.gz"
[[Ogg]]
arch = "x86_64"
git-tree-sha1 = "e8577db74d0b483c3f591ebed089b8e811cc6e79"
os = "freebsd"

    [[Ogg.download]]
    sha256 = "073b73227531a5ea34eb5dd4f96e8e4cb54215b1711a750391cdf9036dc1071a"
    url = "https://github.com/JuliaBinaryWrappers/Ogg_jll.jl/releases/download/Ogg-v1.3.5+0/Ogg.v1.3.5.x86_64-unknown-freebsd.tar.gz"
[[Ogg]]
arch = "x86_64"
git-tree-sha1 = "f55d303ced3dd372b3a43ac5efb59aaed90311cf"
os = "windows"

    [[Ogg.download]]
    sha256 = "cada69785742c96244b2e77814d5c56d9a0e5e5fd990057f74742b5150c79bf2"
    url = "https://github.com/JuliaBinaryWrappers/Ogg_jll.jl/releases/download/Ogg-v1.3.5+0/Ogg.v1.3.5.x86_64-w64-mingw32.tar.gz"
