# Autogenerated wrapper script for Qt5Base_jll for i686-w64-mingw32-cxx03
export libqt5concurrent, libqt5core, libqt5dbus, libqt5gui, libqt5network, libqt5opengl, libqt5printsupport, libqt5sql, libqt5test, libqt5widgets, libqt5xml

using Xorg_libXext_jll
using Xorg_libxcb_jll
using Xorg_xcb_util_wm_jll
using Xorg_xcb_util_image_jll
using Xorg_xcb_util_keysyms_jll
using Xorg_xcb_util_renderutil_jll
using xkbcommon_jll
using Libglvnd_jll
using Fontconfig_jll
using Glib_jll
using Zlib_jll
using CompilerSupportLibraries_jll
using OpenSSL_jll
JLLWrappers.@generate_wrapper_header("Qt5Base")
JLLWrappers.@declare_library_product(libqt5concurrent, "Qt5Concurrent.dll")
JLLWrappers.@declare_library_product(libqt5core, "Qt5Core.dll")
JLLWrappers.@declare_library_product(libqt5dbus, "Qt5DBus.dll")
JLLWrappers.@declare_library_product(libqt5gui, "Qt5Gui.dll")
JLLWrappers.@declare_library_product(libqt5network, "Qt5Network.dll")
JLLWrappers.@declare_library_product(libqt5opengl, "Qt5OpenGL.dll")
JLLWrappers.@declare_library_product(libqt5printsupport, "Qt5PrintSupport.dll")
JLLWrappers.@declare_library_product(libqt5sql, "Qt5Sql.dll")
JLLWrappers.@declare_library_product(libqt5test, "Qt5Test.dll")
JLLWrappers.@declare_library_product(libqt5widgets, "Qt5Widgets.dll")
JLLWrappers.@declare_library_product(libqt5xml, "Qt5Xml.dll")
function __init__()
    JLLWrappers.@generate_init_header(Xorg_libXext_jll, Xorg_libxcb_jll, Xorg_xcb_util_wm_jll, Xorg_xcb_util_image_jll, Xorg_xcb_util_keysyms_jll, Xorg_xcb_util_renderutil_jll, xkbcommon_jll, Libglvnd_jll, Fontconfig_jll, Glib_jll, Zlib_jll, CompilerSupportLibraries_jll, OpenSSL_jll)
    JLLWrappers.@init_library_product(
        libqt5concurrent,
        "bin\\Qt5Concurrent.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5core,
        "bin\\Qt5Core.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5dbus,
        "bin\\Qt5DBus.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5gui,
        "bin\\Qt5Gui.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5network,
        "bin\\Qt5Network.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5opengl,
        "bin\\Qt5OpenGL.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5printsupport,
        "bin\\Qt5PrintSupport.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5sql,
        "bin\\Qt5Sql.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5test,
        "bin\\Qt5Test.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5widgets,
        "bin\\Qt5Widgets.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5xml,
        "bin\\Qt5Xml.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
