[[METIS]]
arch = "aarch64"
git-tree-sha1 = "11f82d168d7024262c2ee48e955b0b962d3bdde0"
os = "macos"

    [[METIS.download]]
    sha256 = "6d2944c724738efd449762dfee3ffff9377ed4693e454090a438efdedb294f6e"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.1+0/METIS.v5.1.1.aarch64-apple-darwin.tar.gz"
[[METIS]]
arch = "aarch64"
git-tree-sha1 = "f0c9fe622a16d4768125a4b965eda218de994b72"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "015bd4cba084210f73d5428fa56b8455129b615aa12a6852893063d6c64107a6"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.1+0/METIS.v5.1.1.aarch64-linux-gnu.tar.gz"
[[METIS]]
arch = "aarch64"
git-tree-sha1 = "28ca473fb25ba4b076fa0d57f37038c327bb789c"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "a0d929b2f8a931b9010fa13da4467c9450b2a47dde7543c3b6f8a6d08208a3a7"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.1+0/METIS.v5.1.1.aarch64-linux-musl.tar.gz"
[[METIS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0e1dfa3f6a05059ed077084d90af0b7e15266c6e"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "fa2540a6bd64153c4b0453fd122159692e3acb7228fb269e52fbf2083cec08a3"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.1+0/METIS.v5.1.1.armv6l-linux-gnueabihf.tar.gz"
[[METIS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ef54bdc5afefb08c84ac38d93256140c4f59ddcc"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "ac80ed790c88af28affd0e934a945d9594af60b0adc621fbc2ae3447bd155a3b"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.1+0/METIS.v5.1.1.armv6l-linux-musleabihf.tar.gz"
[[METIS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fced931300ae09966469e368913556948bb9d9b9"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "a7bd43efeca202aee80d5a8af87bdf90b065e75cd8edd0241f874c69e8e59874"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.1+0/METIS.v5.1.1.armv7l-linux-gnueabihf.tar.gz"
[[METIS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2664ffcac50e4aaa90c6fb1eb2c8befabd2ac42c"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "1d7e1c335d79a76784cf191d77f84cf035cd231e244d1a3957a30bed4c14676d"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.1+0/METIS.v5.1.1.armv7l-linux-musleabihf.tar.gz"
[[METIS]]
arch = "i686"
git-tree-sha1 = "62b723b5af71b4b3fbff5ea812699e034f3d688f"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "e1254d022d10d51a964e0584541d6a4f7f43b5f300d1c3b63aa38a5a425526f2"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.1+0/METIS.v5.1.1.i686-linux-gnu.tar.gz"
[[METIS]]
arch = "i686"
git-tree-sha1 = "44ea2eb536935e300183e0a36e4e750cb059bbc2"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "5e9ba81b58c52dcc3f9b08344bedc04a5f20cdd918549601bfda682c815726eb"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.1+0/METIS.v5.1.1.i686-linux-musl.tar.gz"
[[METIS]]
arch = "i686"
git-tree-sha1 = "05bae971ac556fc24a9b0cfd55cd02543db48a1f"
os = "windows"

    [[METIS.download]]
    sha256 = "77f21017ed4395e09138024ad825b33972a38087f1f22b4b4fd3cc12207f4593"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.1+0/METIS.v5.1.1.i686-w64-mingw32.tar.gz"
[[METIS]]
arch = "powerpc64le"
git-tree-sha1 = "3c9c4a6fac5dd4e1aa7b08856e536109b90c09a5"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "84b389035fb092242905c781bf9bc6ad7ebb31c195fff437c5a80656fca987a9"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.1+0/METIS.v5.1.1.powerpc64le-linux-gnu.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "95df559aa452e5723a113abb7a04a790952083d1"
os = "macos"

    [[METIS.download]]
    sha256 = "ae9db0c3063879e93ac7263f7b3bf398a7f67b93df7a784dc2d35d52292cbe7a"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.1+0/METIS.v5.1.1.x86_64-apple-darwin.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "82a6f6806daf6b9dde345481328ff9f2acc01807"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "81405c9d2f571a6c74dd32521881489309f0ee163182defc2967ab2bf2634b5b"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.1+0/METIS.v5.1.1.x86_64-linux-gnu.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "7169578603f47b96142dc675924c64c072b12753"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "69127e0e8526efd661faeb3500136802352461e0e26df569d098828de4f07160"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.1+0/METIS.v5.1.1.x86_64-linux-musl.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "5c2a401c93c6a9f840ad5d8f2c787eb76cef1ef9"
os = "freebsd"

    [[METIS.download]]
    sha256 = "b152c6ca46392641d03512670550d9d4aaaf876dc9f657eb5924b1ea4b038982"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.1+0/METIS.v5.1.1.x86_64-unknown-freebsd.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "c38d4841e6181c87e6c31d98b8a3fdfeeed70218"
os = "windows"

    [[METIS.download]]
    sha256 = "7889b71c11efd5bcbebe30342c2d0208ee53d3c6ac13848173e47337e6425636"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.1+0/METIS.v5.1.1.x86_64-w64-mingw32.tar.gz"
