language: julia
os:
  - linux
  - osx
julia:
  - 1.2
  - 1.5
notifications:
  email: false

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("Memoize")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
