[[Cgl]]
arch = "aarch64"
git-tree-sha1 = "3bedf79963622bb65c414a1b9dc0cea9d6bdbf77"
os = "macos"

    [[Cgl.download]]
    sha256 = "f2b51fe8d4f93a22c9516d92b6c97c4941fd24e808d106bc9c6498d581b5201e"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.300+0/Cgl.v0.6000.300.aarch64-apple-darwin.tar.gz"
[[Cgl]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "875b30be3b79da3ca0a615d51816de97eedd0858"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "869937ab084ebf4b6ae2b81f587948bcdd8639a2558901bad29e259186b6419f"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.300+0/Cgl.v0.6000.300.aarch64-linux-gnu-cxx03.tar.gz"
[[Cgl]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d7635441525fbe1cd45037f19215a3ad0f002cc6"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "899e580bef3ee27b438d8bf59de42a358737ba0ab0656ad34b511f8dcc91eb07"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.300+0/Cgl.v0.6000.300.aarch64-linux-gnu-cxx11.tar.gz"
[[Cgl]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eae730a103af33d16d124166403090c4ff40ec2c"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "20a5a39054022bec13537131749a91def24a38d134a654dc64f1413e0aab17ea"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.300+0/Cgl.v0.6000.300.aarch64-linux-musl-cxx03.tar.gz"
[[Cgl]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1187ebc1c59b7f61718bb1dbb7640d4634173827"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "0a1e28b83a11da0b78a9cc01f56b7f51df1929cf2b7b432b5a24ef3837d0dda2"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.300+0/Cgl.v0.6000.300.aarch64-linux-musl-cxx11.tar.gz"
[[Cgl]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "97373d1e4c994971d75fa76a64fa2b1a0084eff5"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "2c80c418e2ef38e5d5174637a08ee99931e60e83b4c73c0387927c63f996711c"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.300+0/Cgl.v0.6000.300.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Cgl]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f1ca54aa0c749624750bd017eb40f8135945045b"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "22284b5f7bc62d6ce54d68cafc586c410bd540693151113ce486141dc962eb4f"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.300+0/Cgl.v0.6000.300.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Cgl]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6e587184b52e0e568a11c3e05a75ca10d9a8d6c2"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "a587fc6994a090d11b81a40bb78b59c6ca4c6a73043d78b7fbdb2e33a74f4c24"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.300+0/Cgl.v0.6000.300.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Cgl]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b178e9f57563990d98c332dd037b68c1bd555641"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "3af2578bacdf0b980173ca800fa7d2733576895ecc0f595626d6b322a20eb81f"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.300+0/Cgl.v0.6000.300.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Cgl]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8efa8961d5c9b4ddf2a7be20a113346eb610ce49"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "5edc7def0348989ca683cfc23d0413064d3414c58ecd42bb5732da613bb8d91f"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.300+0/Cgl.v0.6000.300.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Cgl]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c9a9b9dc3494148d678d3cbb1a12db88db15e7f"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "b2228995bb9d57a216b8d964ce6a455b2f12bc2de5764146ba8a454fc7852230"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.300+0/Cgl.v0.6000.300.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Cgl]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d73c99eee033188809d5930cfebe2f4e83fd11b9"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "903f933c0f4b42aef9836a53de371c33593640181d3b641c105a3e2820d5783a"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.300+0/Cgl.v0.6000.300.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Cgl]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "05863fcaa98c7189a99112123b60f4487f4d0064"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "9cc733c1a25b77570b7185281c01c905bd535d5bc68d8d7c4ffb1489af7c3ca2"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.300+0/Cgl.v0.6000.300.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "100094541a93d41eab4387f0cd66fc7f29112e65"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "a824d0ec115ef0f1d560696ade08752de5f15e9f191549fecfff2ff1d405bb4c"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.300+0/Cgl.v0.6000.300.i686-linux-gnu-cxx03.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c9cbf8b9902ea43ca0ef9607ed0acbda021f3129"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "9d227ff63cbff5056f36d5aac865465acffc128b7c08dae87b56649cd01d18b1"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.300+0/Cgl.v0.6000.300.i686-linux-gnu-cxx11.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d2db2a2a765e1bd62bc6b5aaaf94a5657cd5ea6b"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "ce6b7126f9af1965370da351d6def5956ea562b0d3f3bbd1c8b36d6e37a8be32"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.300+0/Cgl.v0.6000.300.i686-linux-musl-cxx03.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7751acbf5f8328f879b834754dd75fa6422434ab"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "5be4c1374eaa69da64651cbbfe0f76c29e87839fab9989c6c6a17d63901c7d2b"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.300+0/Cgl.v0.6000.300.i686-linux-musl-cxx11.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9c25269996905e6bc9fd68298b23801570587524"
os = "windows"

    [[Cgl.download]]
    sha256 = "43cf590f5870f80b9b166483b1edac5b43496a41bcb7adafa648db078e23eb28"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.300+0/Cgl.v0.6000.300.i686-w64-mingw32-cxx03.tar.gz"
[[Cgl]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9faca4cd441ae0617ec311e73935326e1e6c9b17"
os = "windows"

    [[Cgl.download]]
    sha256 = "3fea2098e240c29c57444dd349cd02289fb7cee15f2999fd7dfc86fa222ff686"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.300+0/Cgl.v0.6000.300.i686-w64-mingw32-cxx11.tar.gz"
[[Cgl]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d4d763d24da1d93442638a884f0fe7119d722ca1"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "7ebecfbbfa9d4b7fda4e95d09b01e3f76177959b3260ced5feea37c62dd89ef7"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.300+0/Cgl.v0.6000.300.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Cgl]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c694bdfdb135a458c8d1fd05f3f6d12c356d9ef6"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "bac971d5153dfe60310525b8ac626c94e2cd597354574ba3149dde05d48af10e"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.300+0/Cgl.v0.6000.300.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Cgl]]
arch = "x86_64"
git-tree-sha1 = "cec13b1dcbf91a2de35b1e774fd1193f5246bc40"
os = "macos"

    [[Cgl.download]]
    sha256 = "db60f08fd5cfb463646030557180a8bd3b01d22321bfc40f02a35b4338916372"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.300+0/Cgl.v0.6000.300.x86_64-apple-darwin.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2dff5fe2c664386e2136597276ee7d2dd440ab43"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "8f639128e3cf57d488dbd49bdda8702e0bdb1e227a9bfc9f150658ab780bc14a"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.300+0/Cgl.v0.6000.300.x86_64-linux-gnu-cxx03.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f0bf4ba966efec486e51805b6aef953387d1ce9e"
libc = "glibc"
os = "linux"

    [[Cgl.download]]
    sha256 = "13456024d9b6a552e8cac98ac25278504bfe03b028796154790f0f14c5c82557"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.300+0/Cgl.v0.6000.300.x86_64-linux-gnu-cxx11.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "00745309770491ac33d0d6707e1f89653c0a685c"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "fa100c134356b9e7f33ff2968f0710e4492d93fe49bb63048be2089bbb12a9ea"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.300+0/Cgl.v0.6000.300.x86_64-linux-musl-cxx03.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6b67b048c8d770ac6d41f66862d3ae898081c428"
libc = "musl"
os = "linux"

    [[Cgl.download]]
    sha256 = "10e26742bc1ae0675cb24d2f1a9f251859a80714e712b48233068e766a62ecf0"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.300+0/Cgl.v0.6000.300.x86_64-linux-musl-cxx11.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d990724d6ae3e3c4280eb89ac5001d1f7abf722a"
os = "windows"

    [[Cgl.download]]
    sha256 = "09b8e378b1611cc0b21528a4829f92f337be30634cc4707496d1e110f7a848e5"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.300+0/Cgl.v0.6000.300.x86_64-w64-mingw32-cxx03.tar.gz"
[[Cgl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d3b50fbd93ba61bd29ccd608fba4b15ecf15d02"
os = "windows"

    [[Cgl.download]]
    sha256 = "71bf5000a0be18bafed7903714f6d6dc7ec593c9be70cbebbc0071e9a1f11507"
    url = "https://github.com/JuliaBinaryWrappers/Cgl_jll.jl/releases/download/Cgl-v0.6000.300+0/Cgl.v0.6000.300.x86_64-w64-mingw32-cxx11.tar.gz"
