[[CImGui]]
arch = "aarch64"
git-tree-sha1 = "f1ad48d8f55defc4277f66ba73a252d8dd26649c"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "cc3e97c8fabd4271a1eb2c75b2f63e889a91097ce3f9f68c1d4a99ac5a83215d"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.79.0+0/CImGui.v1.79.0.aarch64-linux-gnu.tar.gz"
[[CImGui]]
arch = "aarch64"
git-tree-sha1 = "6ca8770f358773dd03ac2de173738353e19ea82e"
libc = "musl"
os = "linux"

    [[CImGui.download]]
    sha256 = "527ec9c8934138b50b75d371fec5ecd0b3af5d8bcd42f2e5e741c2f1c4ab702a"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.79.0+0/CImGui.v1.79.0.aarch64-linux-musl.tar.gz"
[[CImGui]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "023f53033fd9300fb772ae1d40f6e388a077feae"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "6eb482ad30f6fc82b735dbf018ab68cd31743828674de1a467b4e8ccc4fed55f"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.79.0+0/CImGui.v1.79.0.armv7l-linux-gnueabihf.tar.gz"
[[CImGui]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2cadb2c878d51aec3dfe58351b32dd4b54b7b95d"
libc = "musl"
os = "linux"

    [[CImGui.download]]
    sha256 = "3b7e13700364a7633f63dfa3f41cb5e9f56f7be004ea3ff0f14245b6af9e51f6"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.79.0+0/CImGui.v1.79.0.armv7l-linux-musleabihf.tar.gz"
[[CImGui]]
arch = "i686"
git-tree-sha1 = "c48dbda6e07db4fbed6196543cb15705fb3b1dbb"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "ad0f21999c7953b18dbb771f37b2b76b0601bc3ddf7e1440729d538500a28e91"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.79.0+0/CImGui.v1.79.0.i686-linux-gnu.tar.gz"
[[CImGui]]
arch = "i686"
git-tree-sha1 = "5302041be91cc3364831976a2befc0e4275e8d53"
libc = "musl"
os = "linux"

    [[CImGui.download]]
    sha256 = "27c4c25d8f8a39d977583de87121bbf2a987964e354f4dbc32d68f95ae7de9d2"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.79.0+0/CImGui.v1.79.0.i686-linux-musl.tar.gz"
[[CImGui]]
arch = "i686"
git-tree-sha1 = "e5d11a966a0ad3d5662c7427871181c8cffd9b9a"
os = "windows"

    [[CImGui.download]]
    sha256 = "0dbc85e7e6b4f030f85f73aa5f85cc339e89febdb94c3c87fd023662401cae29"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.79.0+0/CImGui.v1.79.0.i686-w64-mingw32.tar.gz"
[[CImGui]]
arch = "powerpc64le"
git-tree-sha1 = "ca9725217a577184cbb3c10a2003ec260fd1f246"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "a44b918436ad676545aeafdb4d5182d7d0c9397c0f72640acae18686a72e92d0"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.79.0+0/CImGui.v1.79.0.powerpc64le-linux-gnu.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "d3100d7050700964e317ea7de6b4d73ccf3ae2ef"
os = "macos"

    [[CImGui.download]]
    sha256 = "b1177d5c5227f0947f98dfeef45e6004ed2eeb3c7309ef7e615789ca068af033"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.79.0+0/CImGui.v1.79.0.x86_64-apple-darwin.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "0e6fd9619b85ca51c6999e0b15be8f5e9251aaa8"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "953badede22d16ef03a7ed691cfd70004be28cf5c66c9ea1e90bf10d8a9b024f"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.79.0+0/CImGui.v1.79.0.x86_64-linux-gnu.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "68ab2c46989de3e9cbe5abe74d8189ae11ba8306"
libc = "musl"
os = "linux"

    [[CImGui.download]]
    sha256 = "4d5a71a92834757a2cb5dca2e299881c6c6909ec99d3205bf58482b06728f2cd"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.79.0+0/CImGui.v1.79.0.x86_64-linux-musl.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "434533c7ec8fa7c359754b3747b36aff27253059"
os = "freebsd"

    [[CImGui.download]]
    sha256 = "ccd87a53c67c8924ec29eae013666a14bdb9f8d2bb6da8946322cbe2240cb77d"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.79.0+0/CImGui.v1.79.0.x86_64-unknown-freebsd.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "d94c52f336f108dde7d330d65593b7495aaf6615"
os = "windows"

    [[CImGui.download]]
    sha256 = "d11c2519dd85ebd676ce56222b64f678c961338b38dd50975cdb44a82f19872a"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.79.0+0/CImGui.v1.79.0.x86_64-w64-mingw32.tar.gz"
