[[Expat]]
arch = "aarch64"
git-tree-sha1 = "5e08c6abfa363f0fc73661219a8ba43342b18955"
os = "macos"

    [[Expat.download]]
    sha256 = "99cf0f29fef084de319f3bb6ef517259c6dfd6ad5a34f7033a7e2a7bf51f1ad9"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.10+0/Expat.v2.2.10.aarch64-apple-darwin.tar.gz"
[[Expat]]
arch = "aarch64"
git-tree-sha1 = "5146ad587d0d09290c23dde189ebccb799615640"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "c8c8d36bfed420430702006683514c2c6cdc847776d2443b4d4d446f0c840b44"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.10+0/Expat.v2.2.10.aarch64-linux-gnu.tar.gz"
[[Expat]]
arch = "aarch64"
git-tree-sha1 = "4346c24699ba99475b4e37ef772096aeb27d34ae"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "97605a0e39d0bf0806c67426ee19aa9b467d733394936edc8472f259bec08d28"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.10+0/Expat.v2.2.10.aarch64-linux-musl.tar.gz"
[[Expat]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f574e3f70202d8b7c306c515d4302ef5c3f207e7"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "544dda0d87dad258d9d0e6a42a70b6fedabff2ef0c7a46df5e1ed30413304bb0"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.10+0/Expat.v2.2.10.armv6l-linux-gnueabihf.tar.gz"
[[Expat]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "566a8c6b79cae08f199e842e90af3fbe51f87cd9"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "f4591c9f3a8487b2c94b261121c3218619444eb354f31ffc19bc8242d7ae637d"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.10+0/Expat.v2.2.10.armv6l-linux-musleabihf.tar.gz"
[[Expat]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cc8348f34d90bef1006603706c7e0b842749349d"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "693c793aec96b4d193ed496f9b15f9c8acedb49c89f483e3658e39f86ec7a167"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.10+0/Expat.v2.2.10.armv7l-linux-gnueabihf.tar.gz"
[[Expat]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "78f00690401bef44b326fd8682f9f0cc37df469a"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "fb22616564a8556cbae259601bac7cc73ad269f4d66980bef9540b97b61912eb"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.10+0/Expat.v2.2.10.armv7l-linux-musleabihf.tar.gz"
[[Expat]]
arch = "i686"
git-tree-sha1 = "aebda03821378527b94800c6d673e97c70772576"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "e9a16366459b682d0ae7d35b3e9648cf1be2becf783c56219a39c8577585be1c"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.10+0/Expat.v2.2.10.i686-linux-gnu.tar.gz"
[[Expat]]
arch = "i686"
git-tree-sha1 = "2b9b124986581f725981d6b954495fee4eca6bf6"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "3a43ab346f8d78e8a6abf54e184bca720307f76702a0faec4151a677e2bda596"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.10+0/Expat.v2.2.10.i686-linux-musl.tar.gz"
[[Expat]]
arch = "i686"
git-tree-sha1 = "78b40899bf9dd9b504c87112a0f3199d7e18f9d1"
os = "windows"

    [[Expat.download]]
    sha256 = "22e071840384ec8b0b038b96bc81c00f10b834c30aaba1b244d161d1445388ec"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.10+0/Expat.v2.2.10.i686-w64-mingw32.tar.gz"
[[Expat]]
arch = "powerpc64le"
git-tree-sha1 = "26e34b1a45bac7678389b68b06ebce3f4e332988"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "4e889615bd19b629b4e109ba9271f5c456c016a98f009045df97062c26746a5f"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.10+0/Expat.v2.2.10.powerpc64le-linux-gnu.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "d3cdfef027f1989b22b9b8b540872339aa1e2cbc"
os = "macos"

    [[Expat.download]]
    sha256 = "193d7878d2025e1c52d161e6652e5345bec328343a214562631feb176ea759cc"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.10+0/Expat.v2.2.10.x86_64-apple-darwin.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "2a0fba617ae96fd7bec0e5f0981a2cc395998f08"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "ac7aa7d1a3e820111c0ae33a76c8d0580792ba4b7ce9b252489c8ad0e30dab7f"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.10+0/Expat.v2.2.10.x86_64-linux-gnu.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "ed53cbc4b967e61078ffe515bef8d275a35d2542"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "0463b64f6d6baaaa12cca884968be9a341048a96216082122c43fd2dcbf2e6eb"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.10+0/Expat.v2.2.10.x86_64-linux-musl.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "73e38f257377076183ece9e15e44165998b5a1b5"
os = "freebsd"

    [[Expat.download]]
    sha256 = "b9eab6e821d0bceec2716d053b75cb4a34eba07a38f9d41bfdaf93d112d26ade"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.10+0/Expat.v2.2.10.x86_64-unknown-freebsd.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "da217cb572f799c2f8eebc4a732db91b037bdccd"
os = "windows"

    [[Expat.download]]
    sha256 = "794b78041345058a93d35b01e977547b66d297e474a73d5043057553dfa52055"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.10+0/Expat.v2.2.10.x86_64-w64-mingw32.tar.gz"
