[[JpegTurbo]]
arch = "aarch64"
git-tree-sha1 = "4b9e12a08aadf7e5341ff4c2b56fa26bfacf6e97"
os = "macos"

    [[JpegTurbo.download]]
    sha256 = "95628f1dc9132a6c69728549056fcf17b970f7817bdf937320ba59d5b7b1fa3a"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.1.0+0/JpegTurbo.v2.1.0.aarch64-apple-darwin.tar.gz"
[[JpegTurbo]]
arch = "aarch64"
git-tree-sha1 = "d2ac5a02adbb01ca99aa5d269dae708cbc45baa0"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "053d0fe6fc7c31e435184d99c299eaf6355c5ec98a2efba638324503a831a75a"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.1.0+0/JpegTurbo.v2.1.0.aarch64-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "aarch64"
git-tree-sha1 = "f0b6917f8ac81c839f21f3ca4a2d87ee2c631da0"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "d9d73168cc74d8d084ed86cb540bf0c4977413a61366b53752fc592851d65ecd"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.1.0+0/JpegTurbo.v2.1.0.aarch64-linux-musl.tar.gz"
[[JpegTurbo]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3518f9bdeadad404df304365bc944d212982023a"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "d19c141d8fd056c59ce2106a7655eb29f531f261393ed1568f37281f21b6d4e1"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.1.0+0/JpegTurbo.v2.1.0.armv6l-linux-gnueabihf.tar.gz"
[[JpegTurbo]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3b434739692b16fec8dfe8cde34b30f9e1133996"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "478e123e02e678905a7f4f85862be3b9be4c2bb34e5d8e6b6c87208c47a1b540"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.1.0+0/JpegTurbo.v2.1.0.armv6l-linux-musleabihf.tar.gz"
[[JpegTurbo]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "650dd90073b8741931b1b0cc5026743f2e488770"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "cbfca06a07e18a9cb48c6828acbbe0384297af854a527fdc1fca1dac9d2f38e2"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.1.0+0/JpegTurbo.v2.1.0.armv7l-linux-gnueabihf.tar.gz"
[[JpegTurbo]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4f94f762e9cf3135b6cae1c6c8f7f3b25403aa40"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "19e62119047b7ddb4f82bce512f48040b0cab99a431d37ceb9327d19d7684f26"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.1.0+0/JpegTurbo.v2.1.0.armv7l-linux-musleabihf.tar.gz"
[[JpegTurbo]]
arch = "i686"
git-tree-sha1 = "ef9d568a375556076dd7b4175885818db331b93b"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "b5b671de8cb0bf6bced841f75fe77fc7429502c26a75cc701de77a9e7e65e104"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.1.0+0/JpegTurbo.v2.1.0.i686-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "i686"
git-tree-sha1 = "57a791cc771e6380a1025f642e8029410ef131a6"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "575a5d584447abe5c89bec531d4e1a5ff91e1938ca4b81ffbe590a919a74dc7f"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.1.0+0/JpegTurbo.v2.1.0.i686-linux-musl.tar.gz"
[[JpegTurbo]]
arch = "i686"
git-tree-sha1 = "5660bdc98314ce59a4aed145277a614d55253c4d"
os = "windows"

    [[JpegTurbo.download]]
    sha256 = "597a021dcd754374800d5813e0e9b203eb9b92ad908b59218aff1dae67a7311a"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.1.0+0/JpegTurbo.v2.1.0.i686-w64-mingw32.tar.gz"
[[JpegTurbo]]
arch = "powerpc64le"
git-tree-sha1 = "7a1b7d017f67d157412d39a665a5030de7a7939c"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "7f113eb9f1b53cb8ab07df2340b34293ae611149664833c2ac0802b9ebc342ea"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.1.0+0/JpegTurbo.v2.1.0.powerpc64le-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "b67e1281926ad9756413f8c733073aa5d2784f43"
os = "macos"

    [[JpegTurbo.download]]
    sha256 = "59534c15a16c10871f4052320002a335f65bb260673456cfcfa75c5be569c16c"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.1.0+0/JpegTurbo.v2.1.0.x86_64-apple-darwin.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "b9b138178f2c19d38aa8a19eac1c256f54bb6234"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "15557cb4dfca736bedc2f43d09441f9566ce943deaf2d4e6065f4dccbf855b7f"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.1.0+0/JpegTurbo.v2.1.0.x86_64-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "dff2410da150615f1c569712845e251d13bb5a87"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "05a20771ddd079bd5a460a54d3223fccac47a1089142595a1a7fc16748f4f303"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.1.0+0/JpegTurbo.v2.1.0.x86_64-linux-musl.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "f00e221d56b10c230a4adfd41ec38386b1c24f13"
os = "freebsd"

    [[JpegTurbo.download]]
    sha256 = "853c8c73e90710a384503b4bfde9e43e64a1454ed9d3174d6bf86130ed383ae6"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.1.0+0/JpegTurbo.v2.1.0.x86_64-unknown-freebsd.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "55e933ea6d32118b47ad5711b5f556cec1bdfa84"
os = "windows"

    [[JpegTurbo.download]]
    sha256 = "62cb61e0638a687688dcabcd676527f3194524b4a60f8bcb5582ab64791ff580"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.1.0+0/JpegTurbo.v2.1.0.x86_64-w64-mingw32.tar.gz"
