# Autogenerated wrapper script for CImGui_jll for x86_64-apple-darwin
export compile_commands, libcimgui, libcimgui_helper, libimgui

JLLWrappers.@generate_wrapper_header("CImGui")
JLLWrappers.@declare_file_product(compile_commands)
JLLWrappers.@declare_library_product(libcimgui, "@rpath/libcimgui.dylib")
JLLWrappers.@declare_library_product(libcimgui_helper, "@rpath/libcimgui_helper.dylib")
JLLWrappers.@declare_library_product(libimgui, "@rpath/libimgui-cpp.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        compile_commands,
        "share/compile_commands.json",
    )

    JLLWrappers.@init_library_product(
        libcimgui,
        "lib/libcimgui.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcimgui_helper,
        "lib/libcimgui_helper.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libimgui,
        "lib/libimgui-cpp.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
