# Autogenerated wrapper script for Osi_jll for i686-w64-mingw32-cxx11
export libOsi, libOsiCommonTests

using CoinUtils_jll
using OpenBLAS32_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("Osi")
JLLWrappers.@declare_library_product(libOsi, "libOsi-1.dll")
JLLWrappers.@declare_library_product(libOsiCommonTests, "libOsiCommonTests-1.dll")
function __init__()
    JLLWrappers.@generate_init_header(CoinUtils_jll, OpenBLAS32_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libOsi,
        "bin\\libOsi-1.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libOsiCommonTests,
        "bin\\libOsiCommonTests-1.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
