# Autogenerated wrapper script for ASL_jll for aarch64-apple-darwin
export libasl

JLLWrappers.@generate_wrapper_header("ASL")
JLLWrappers.@declare_library_product(libasl, "@rpath/libasl.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libasl,
        "lib/libasl.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
