# Autogenerated wrapper script for Cgl_jll for x86_64-w64-mingw32-cxx11
export libCgl

using Clp_jll
using Osi_jll
using CoinUtils_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("Cgl")
JLLWrappers.@declare_library_product(libCgl, "libCgl-1.dll")
function __init__()
    JLLWrappers.@generate_init_header(Clp_jll, Osi_jll, CoinUtils_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libCgl,
        "bin\\libCgl-1.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
